# Generated by Django 4.2 on 2023-04-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistilledOxygen',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'CM_PID_DO/Process_DO',
            },
        ),
        migrations.CreateModel(
            name='pH',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'CM_HAM_PH_AI1/pH_value',
            },
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'CM_PRESSURE/Output',
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'CM_HAM_DO_AI1/Temp_value',
            },
        ),
    ]
