# Generated by Django 4.2 on 2023-05-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='distilledoxygen',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ph',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pressure',
            table=None,
        ),
        migrations.AlterModelTable(
            name='temperature',
            table=None,
        ),
    ]
